# Twitch Drop Tracker - Chrome Extension Zip Config

include:
  - manifest.json
  - background.js
  - content-isolated.js
  - content-main.js
  - i18n.js
  - fullpage/**/*
  - icons/**/*
  - locales/**/*
  - popup/**/*
  - shared/**/*

exclude: []
